server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** #搜索微服务的印射路径
    user-service: /user/** #用户微服务的印射路径
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** #购物车微服务
  add-host-header: true
  sensitive-headers: null
leyou:
  jwt:
    pubKeyPath: /Users/wangsiwei/Desktop/E-shopApplication/RSA/rsa.pub
    expire: 30
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

